//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoCiencias.Intranet.CrossCutting.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AlertResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AlertResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrupoCiencias.Intranet.CrossCutting.Common.Resources.AlertResources", typeof(AlertResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Se procesó correctamente..
        /// </summary>
        public static string msg_correcto {
            get {
                return ResourceManager.GetString("msg_correcto", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error en el método GetRegisteredPaymentInformationAsync..
        /// </summary>
        public static string msg_error_metohd_register_payment {
            get {
                return ResourceManager.GetString("msg_error_metohd_register_payment", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Hubo un error, el Objeto create_payment está null..
        /// </summary>
        public static string msg_null_variable {
            get {
                return ResourceManager.GetString("msg_null_variable", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El usuario no se encuentra registrado en la aplicación.
        /// </summary>
        public static string str_error_key_no_encontrado {
            get {
                return ResourceManager.GetString("str_error_key_no_encontrado", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a El method -&gt; SetListaMasterDetail ha retornado con un valor NULL .
        /// </summary>
        public static string str_error_method_master {
            get {
                return ResourceManager.GetString("str_error_method_master", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ERROR.
        /// </summary>
        public static string str_log_error {
            get {
                return ResourceManager.GetString("str_log_error", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a INFORMATION.
        /// </summary>
        public static string str_log_info {
            get {
                return ResourceManager.GetString("str_log_info", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a WARNING.
        /// </summary>
        public static string str_log_warning {
            get {
                return ResourceManager.GetString("str_log_warning", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a INFO : METHOD -&gt;.
        /// </summary>
        public static string str_method {
            get {
                return ResourceManager.GetString("str_method", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a INFO : response -&gt;.
        /// </summary>
        public static string str_response {
            get {
                return ResourceManager.GetString("str_response", resourceCulture);
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a INFO : URL -&gt;.
        /// </summary>
        public static string str_url {
            get {
                return ResourceManager.GetString("str_url", resourceCulture);
            }
        }
    }
}
